language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: pUTxIvGP+t9DbpfJQV22ng4OGjUCqUm4WvqlLgK8hPOJXeQvCxe50pmqdhZIK7yhbSwu/dhg/pg4nlaOXkkJZXyzyEXBKEZCepKjBE9F7Ws8v5LL7t3YYAR1NUzLFray51z16us54JpvlWknDK9dN+xe8JrbJ6LVlGq5AW9jQ5kZkWBUXKUk8OkG+RTBN4xOC2kCg7VEfmgO20F0Y8NjOeLCgh5p+1iIig141YDi3hKpzb7IaAdtNUUoDVEY+TiMIm3sH77E2hafHyAgFi4fAZo3qz3jBMXTPVRfLBWsCoOEJpYkjAscIMWh961XRwpD1c2Kw+XbpTb8dRnihIx45R9JL+qgBwZ3/l7bPSatETY3ja5PezhunraC8Bnz9CbJo+/tow4serH9JuYOJF8CchmCBOAU+6jezLPyrUqhlTQuopMIU2wVhUDwBVJxF1PxaImYTo+CUnccncgZBsVCXAakmezWgvLHxFWUx3C2dUL6LooVXmpl9hypvM8vFszlwuVdUAnpq8t8hTsHayyBChhy05meRJQ+tQrq2vA/RdPPlK3iXRKlSjk18vwZC5GJeG3KebOnlziQvPPMReoDRBpyWaDFY61GokpuJkqNTy/OlJ9RHNWNBnz8FtqSTacZbqdbu2oKWExZTlsrSx1bOtJuMA0Pr/L7D83hu+Vzeo0=
  app: stark-mesa-50807
  on:
    repo: jsurt/react-capstone-api
